### ISSUE TITLE
Error: The login credentials you entered do not match our records.

### ISSUE THREAD

**Issue by SneakerFreaker64** [xballoy/coros-api#11]
```
Error: The login credentials you entered do not match our records.
    at login (file:///Users/focus/Documents/GitHub/coros-api/src/service/login.ts:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/focus/Documents/GitHub/coros-api/src/index.ts:41:29
```

I get this error even if I put the right credentials unfortunately.
It seems like the code doesn't work anymore ?

**Comment by SneakerFreaker64** [comment]
I found the issue, it wont recognize any special symbol in the password. Therefore you have to change your password to one without special symbols.

**Comment by xballoy** [comment]
If you are able to log https://t.coros.com/login I should be able to make this work. What was the special symbol that causes an issue?

**Comment by xballoy** [comment]
Closing, please reopen a new issue with more info if you want me to fix this.
