### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by jvarsoke** [xballoy/coros-api#215]
Having not updated for a while (6mo), but using the tool successfully, I did a git pull today.

$ sudo npm install  #bringing me up to 10.7.0
npx nest start -- export-activities -o ~/docs/run/coros/ --exportType fit --fromDate 2024-10-21

Output is as follows:
```
✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
>  SWC  Running...
Successfully compiled: 16 files with swc (122.13ms)
[Nest] 160199  - 10/21/2024, 3:10:43 PM     LOG [NestFactory] Starting Nest application...
[Nest] 160199  - 10/21/2024, 3:10:43 PM     LOG [InstanceLoader] CommandRootModule dependencies initialized +20ms
[Nest] 160199  - 10/21/2024, 3:10:43 PM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 160199  - 10/21/2024, 3:10:43 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 160199  - 10/21/2024, 3:10:43 PM     LOG [InstanceLoader] CommandRunnerModule dependencies initialized +0ms
[Nest] 160199  - 10/21/2024, 3:10:43 PM     LOG [InstanceLoader] CorosModule dependencies initialized +0ms
[Nest] 160199  - 10/21/2024, 3:10:43 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 160199  - 10/21/2024, 3:10:50 PM   ERROR [CommandFactory] ValidationError: 0 => Required
1 => Required
2 => Required
```
Any suggestions?

**Comment by xballoy** [comment]
Hello @jvarsoke,
I just pushed a new version that improves the logging of the validation error.
In your case I think there is no data returned by the API due to the filter you sent (you filter from today).

**Comment by jvarsoke** [comment]
Ah yes.  I think the watch hadn't synced with the App yet.  I got a little ahead of myself.

Hopefully the error message you added is a bit more in the lines of "no activities to download" or something.

Thanks so much.

**Comment by xballoy** [comment]
I added fix for the validation error (the API didn't respond with the expected data) but now that you suggested it I also added a "No activities found" message.
