### ISSUE TITLE
Only offers usage options upon run

### ISSUE THREAD

**Issue by jvarsoke** [xballoy/coros-api#43]
This is likely user error, but since the instructions are so simple, I'm failing to figure out where it's going wrong.

npm version: 10.5.0
nodejs version: 18.20.2

from ./ of the project

--cut--
$ npm start -- export-activities -o ~/Downloads

> coros-api@2.0.0 start
> nest start export-activities -o /home/Downloads

Successfully compiled: 15 files with swc (127.38ms)
Usage: main [options] [command]

Options:
   -h, --help display help for command
Commands:
  export-activities [options] Bulk export your Coros activities
  help [command]
$
--cut--

Other than typing "help" after "--", nothing provides any different output (that I've tried).

Thanks for any help you can provide.

**Comment by xballoy** [comment]
My mistake I just fixed the readme, the right command is `npx nest start ...` instead of `npm start ...` otherwise are not properly passed to the command.

Can you please confirm this is working now?

**Comment by jvarsoke** [comment]
Thanks.  I think this got me a bit farther. Receiving:

ValiError: Invalid type: Expected string but received undefined[main]

(note a I have populated .env file based on your provided example)

**Comment by xballoy** [comment]
You found an actual bug ([fixed](https://github.com/xballoy/coros-api/commit/66ff893f94ccd0c10a7b55bfdb9b5df09fc6518d)) 🎉 

When we did not specify a file type there was an issue.

Should be good now!
