### ISSUE TITLE
Trouble with authenticating API calls 

### ISSUE THREAD

**Issue by ma2ciek** [xballoy/coros-api#9]
For some reason after I log in and get the access token I'm getting `Error: Access token is invalid` during the second API call (`queryActivities`) - have you maybe experienced similar issue?

**Comment by xballoy** [comment]
I never had this issue. I just tried and I'm able to get the fit files so the API didn't change.
I'm guessing the password is correct because otherwise you would have an error on the login call.

Can you retry, maybe it was an issue on Coros side.
